name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - uses: pre-commit/action@v3.0.0

  pytest:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: s3cr3t
    steps:
    - name: Checkout Code Repository
      uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
    - run: python -m pip install poetry
    - run: poetry install --with dev
    - run: poetry run pytest
